### ISSUE TITLE
SimpleSAMLPHP v2.x - issue with class inheritance

### ISSUE THREAD

**Issue by clmcavaney** [aidan-/SimpleTOTP#12]
G'day @aidan-,
I have been using your SimpleTOTP module with a SimpleSAMLPHP v1.x installation, and am now trying to upgrade to v2.x
I realise that you may not be actively working in this space any more, but was wondering if your PHP insights may be able to assist.

I am hitting this error:
```
SimpleSAML\Error\UnserializableException: Could not resolve 'simpletotp:2fa': The class 'SimpleSAML\Module\simpletotp\Auth\Process\2fa' isn't a subclass of '\SimpleSAML\Auth\ProcessingFilter'.
```

I have modified the class definition from:
```
class sspmod_simpletotp_Auth_Process_2fa extends SimpleSAML_Auth_ProcessingFilter
```
to
```
use SimpleSAML\Auth;
...
class sspmod_simpletotp_Auth_Process_2fa extends Auth\ProcessingFilter
```

So, from what I understand, through the `extends` keyword, the class "sspmod_simpletotp_Auth_Process_2fa" class is a sub class of `SimpleSAML\Auth\ProcessingFilter`.

Do you have any pointers?

**Comment by clmcavaney** [comment]
I think this may be due to the method being called 2fa and that a number can't be the first character of a function name.
If I change it to `mfa` it appears to be working now.

Now for a template migration to the twig engine.

**Comment by clmcavaney** [comment]
Righto - so I think the name of the class was the issue.
With a bit of `twig` migration of the template, I think I have a working prototype ready.
I will put it under revision control and submit a pull request at some point.

**Comment by aidan-** [comment]
@clmcavaney , thank you for putting the effort in getting this module working with SSP v2.0! I've put some quick comments in the PR and will be happy to merge once they are addressed.

**Comment by aidan-** [comment]
Closing now that #13 is merged
