### ISSUE TITLE
SimpleTotp not working 

### ISSUE THREAD

**Issue by wiryonolau** [aidan-/SimpleTOTP#3]
After login no totp request and ga_secret is not removed

**Comment by aidan-** [comment]
Have you placed the necessary authproc configurations in the right place? What versions are you using? What does your configuration look like?  Do you have SimpleSAMLPHP debug output you can share?

**Comment by Wiryono** [comment]
Here is my configuration

I use the default installation and add write the configuration in config/config.php
Here is the config [samltotp.txt](https://github.com/aidan-/SimpleTOTP/files/96836/samltotp.txt)

Currently no error from httpd or php, I haven't setup simplesamlphp in debug mode I'll check later

**Comment by aidan-** [comment]
Have you had any luck with debugging on your end?  I have tested and can confirm that the module is still working as expected.  What does your test environment look like?

Looking at your config, it looks like you are getting the IDP to execute the SimpleTOTP module.  You need to make sure you are testing with a separate SP as opposed to just using the `Test configured authentication sources` method as it does not execute auth processing filters.

**Comment by milindson** [comment]
I have configured the SimpleTOTP as mentioned. But nothing is working. Can you please provide me the exact steps to configure SimpleTOTP.

**Comment by trf000** [comment]
Is this still being maintained? I'm running SimpleSamlPhp 1.18.3. I'd really like some detailed instructions on just how to fully enable this.

**Comment by aidan-** [comment]
This module is not being actively maintained by myself as I no longer have personal use for it.  Though, I'm happy to accept/review PRs for enhancements.  If there is interest from serious contributors I can look at giving them push permissions/or they can fork it.
