### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by M1k13** [aidan-/SimpleTOTP#8]
Hey,

Can you please provide an install guide with the steps?
I tried it my self but i get a : SimpleSAML\Error\CriticalConfigurationError: The configuration is invalid: The configuration (config/config.php) is invalid: Missing configuration file

Backtrace:
0 www/_include.php:70 (N/A)

**Comment by aidan-** [comment]
This sounds more like a general SimpleSAMLPHP configuration issue.
