### ISSUE TITLE
new UI twig template

### ISSUE THREAD

**Issue by Yzed** [aidan-/SimpleTOTP#9]
for upcoming 1.70 release a twig template is needed

**Comment by aidan-** [comment]
This should be resolved in #13

**Comment by clmcavaney** [comment]
**Note** that the updates in #13 may not be backward compatible to version 1.x of SSP.
Specifically I am referring to [Twig: Migrating templates](https://github.com/simplesamlphp/simplesamlphp/wiki/Twig:-Migrating-templates#:~:text=Note%3A%20Do%20not%20delete%20the%20php%20template%20yet!)

**Comment by aidan-** [comment]
Closing now that #13 is merged
